M48
; DRILL file {KiCad 9.0.7} date 2026-03-06T16:12:08+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-06T16:12:08+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X142.714Y-64.501
T2
X117.939Y-95.744
X117.939Y-120.254
X164.889Y-95.744
X164.889Y-120.254
M30
